routes/web.php
    Route::get('/growthstocks/print_bulk_number/{bulk_number}', 'GrowthRoomStockController@printBulkNumber');

    // Initiation Stock
    Route::get('/initiations/create', 'InitiationController@create')->name('initiations.create');
    Route::get('/initiations/growth_room', 'InitiationController@growthRoom')->name('initiations.growth');
    Route::get('/initiations/transfer_room', 'InitiationController@transferRoom')->name('initiations.transfer');
    Route::get('/initiations/to_transfer_room/{id}', 'InitiationController@toTransferRoom')->name('initiations.transfer_move');
    Route::get('/initiations/to_growth_room/{id}', 'InitiationController@toGrowthRoom')->name('initiations.growth_move');
    Route::get('/initiations/to_prod_transfer_room/{id}', 'InitiationController@toProdTransferRoom')->name('initiations.prod_transfer_move');
    Route::get('/initiations/to_rnd_transfer_room/{id}', 'InitiationController@toRndTransferRoom')->name('initiations.rnd_transfer_move');
    Route::post('/initiations/store', 'InitiationController@store')->name('initiations.store');


    // reports
    Route::get('/reports/performance', 'ReportsController@performance')->name('performance');
    Route::post('/reports/performance', 'ReportsController@performance')->name('reports.filter');
    Route::get('/reports/room_conditions', 'ReportsController@room_conditions')->name('room_conditions');
    Route::get('/reports/customer_reports/{id}', 'ReportsController@customerReports')->name('customer_reports');
    Route::get('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status');
    Route::post('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status.filter');
    Route::get('/reports/bulk_status/', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/bulk_status/{status}', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status');
    Route::post('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status.filter');

    Route::get('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock');
    Route::post('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock.filter');
    Route::get('/reports/week_bulk/{plant_id}/{year}/{week}/{media_id?}/{plant_size?}/', 'ReportsController@weekBulk')->name('weekBulk');

    Route::post('/reports/achievement', 'ReportsController@achievement')->name('operator.achievement');

    // Performance Breakdown
    Route::get('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd');
    Route::post('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd.filter');

    // Contamination Report
    Route::get('/reports/contamination', 'ReportsController@contamination')->name('contamination');
    Route::post('/reports/contamination', 'ReportsController@contamination')->name('contamination.filter');

    // Cutters performance
    Route::get('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');
    Route::post('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');

    // Visualization
    Route::resource('visualization', 'VisualizationController');
    Route::post('visualization/index', 'VisualizationController@index')->name('visualization.filter');
    Route::get('visualization/show', 'VisualizationController@show')->name('visualization.sales');
    Route::post('visualization/show', 'VisualizationController@show')->name('visualization.sales.filter');
    //tasks
    Route::get('/tasks/mark_completed/{id}', 'TaskController@mark_completed')->name('tasks.mark_completed');

    //orders
    Route::delete('/orders/destroy_order_item/{id}', 'OrderController@destroyOrderItem')->name('orders.destroy_order_item');
    Route::post('/orders/store_order_item', 'OrderController@storeOrderItems')->name('orders.store_order_item');


    // backend
    Route::get('/backend/find_bulk_number', 'BackEndController@findBulkNumber');
    Route::post('/backend/find_bulk_number', 'BackEndController@findBulkNumber')->name('findBulkNumber');
    Route::post('/backend/update_bulk_number', 'BackEndController@updateBulkNumber')->name('updateBulkNumber');
    Route::post('/backend/update_bulk_completed', 'BackEndController@updateBulkCompleted')->name('updateBulkCompleted');
    Route::get('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('setCustomersToPlant');
    Route::post('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('storeCustomersToPlant');
    Route::post('/backend/transfer_bulk', 'BackEndController@transferBulk')->name('transferBulk');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

    Route::get('/backend/find_media', 'BackEndController@findMedia');
    Route::get('/backend/get_media_plant_contamination/{media_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getMediaPlantContamination')->name('mediaPlantContamination');
    Route::post('/backend/find_media', 'BackEndController@findMedia')->name('findMedia');

    Route::get('/backend/find_container', 'BackEndController@findContainer');
    Route::get('/backend/get_container_plant_contamination/{container_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getContainerPlantContamination')->name('containerPlantContamination');
    Route::post('/backend/find_container', 'BackEndController@findContainer')->name('findContainer');

    Route::get('/backend/{user_id}/set_relationships', 'BackEndController@setRelationships')->name('setRelationships');


    // download apk file
    Route::get('/backend/download/{file}', 'BackEndController@download')->name('download_apk');

    Route::delete('/backend/deleteBulk/', 'BackEndController@deleteBulk')->name('deleteBulk');
    Route::delete('/backend/deleteSerialNumber/', 'BackEndController@deleteSerialNumber')->name('deleteSerialNumber');

    // greenhouse
    Route::post('/greenhouses', 'GreenhouseController@index')->name('greenhouses.filter');
    Route::post('/greenhouses/store', 'GreenhouseController@store')->name('greenhouses.store');
    Route::post('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::post('/greenhouses/sold', 'GreenhouseController@sold')->name('greenhouses.sold');
    Route::post('/greenhouses/reserve_stock', 'GreenhouseController@reserveStock')->name('greenhouses.reserve_stock');
    Route::get('/greenhouses/{id}/reserve', 'GreenhouseController@reserve')->name('greenhouses.reserve');
    Route::get('/greenhouses', 'GreenhouseController@index')->name('greenhouses.index');
    Route::get('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::get('/greenhouses/{id}/sell', 'GreenhouseController@sell')->name('greenhouses.sell');
    Route::get('/greenhouses/{id}/cancel', 'GreenhouseController@cancel')->name('greenhouses.cancel');
    Route::get('/greenhouses/{id}/plant_create', 'GreenhouseController@plantCreate')->name('greenhouses.plant_create');
    Route::get('/greenhouses/show/{id}/{task_id}', 'GreenhouseController@show');
    Route::get('/greenhouses/plants/{id}', 'GreenhouseController@plants');

    //RetailCustomer
    Route::get('/retail_customers/{id}/print_address', 'RetailCustomerController@printAddress')->name('retail_customers.print_address');

    //SalesRecords
    Route::get('sales_records', 'SalesRecordController@index');
    Route::get('/sales_records/{invoice_number}/invoiceNumber', 'SalesRecordController@invoiceNumber')->name('invoiceNumber');

    // Label Printers
    Route::get('printers', 'PrinterController@index');
    Route::get('printers/{id}/edit', 'PrinterController@edit')->name('printer.edit');
    Route::post('printers/store', 'PrinterController@store')->name('printer.store');
    Route::patch('printers/update/{id}', 'PrinterController@update')->name('printer.update');

    // Media requests
    Route::get('media_requests/cancel/{id}', 'MediaRequestController@cancel')->name('media_requests.cancel');
    Route::get('media_requests/revert/{id}', 'MediaRequestController@revert')->name('media_requests.revert');

    Route::resource('shares', 'ShareController');
    Route::resource('medias', 'MediaController');
    Route::resource('mediastocks', 'MediaStockController');
    Route::resource('growthstocks', 'GrowthRoomStockController');
    Route::resource('categories', 'CategoryController');
    Route::resource('reasons', 'ReasonController');
    Route::resource('subcategories', 'SubCategoryController');
    Route::resource('users', 'UserController');
    Route::resource('containers', 'ContainerController');
    Route::resource('items', 'ItemController');
    Route::resource('frequencies', 'FrequencyController');
    Route::resource('tasks', 'TaskController');
    Route::resource('companies', 'CompanyController');
    Route::resource('customers', 'CustomerController');
    Route::resource('retail_customers', 'RetailCustomerController');
    Route::resource('sales_records', 'SalesRecordController');
    Route::resource('orders', 'OrderController');
    Route::resource('greenhouses', 'GreenhouseController', ['except' => ['store']]);
    Route::resource('roles', 'RoleController');
    Route::resource('media_requests', 'MediaRequestController');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('media/autocomplete', 'MediaController@autocomplete')->name('media.autocomplete');
Route::get('item/autocomplete', 'ItemController@autocomplete')->name('item.autocomplete');
Route::get('sales/autocomplete', 'SalesRecordController@autocomplete')->name('sales.autocomplete');

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $table = 'sub_cat';
    public $timestamps = false;

    protected $fillable = ['cat_id, subcat'];

    public function category()
    {
        return $this->belongsTo('App\Category', 'cat_id');
    }

    public function items()
    {
        return $this->hasMany('App\Item', 'sub_cat');
    }

    public function scopeActive($query)
    {
        return $query->where('active', 1);
    }

    public function scopeInActive($query)
    {
        return $query->where('active', 0);
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\SubCategory;
use Illuminate\Http\Request;
use App\Category;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::orderBy('name')->where('active', 1)->get();
        if ($request->has('select_inactive')) {
            $subcategories = SubCategory::inActive()->get();
        } else {
            $subcategories = SubCategory::active()->get();
        }
        return view('subcategories.index', ['subcategories' => $subcategories, 'categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

       //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'sub_category_name'=>'required',
            'cat_id'=>'required',
        ]);
        $sub_cat = new SubCategory();

        $sub_cat->cat_id = $request->get('cat_id');
        $sub_cat->subcat = $request->get('sub_category_name');

        if ($sub_cat->save()){
            return redirect('/subcategories')->with('success', 'Sub Category has been added');
        }

        return back()->withInput()->with('error', 'Could not add Sub Category');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sub_category = SubCategory::find($id);
        return view('subcategories.show', ['sub_category' => $sub_category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subCategory = SubCategory::find($id);
        $categories = Category::all();
        //dd($subCategory);

        return view('subcategories.edit', compact('subCategory', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'category_name'=>'required',
            'subCategory_name'=> 'required'
        ]);

        $subCategory = SubCategory::find($id);

        $subCategory->cat_id = $request->get('category_name');
        $subCategory->subcat = $request->get('subCategory_name');
        $subCategory->active = $request->get('active');

        if ($subCategory->save()){
            return redirect('/subcategories')->with('success', 'Sub Category has been updated');
        }

        return back()->withInput()->with('error', 'Could not add Sub Category');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SubCategory  $subCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $media = SubCategory::find($id);
        $media->delete();

        return redirect('/subcategories')->with('success', 'Sub Category has been deleted Successfully');
    }
}

resources/views/subcategories/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Edit Media
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif
            <form method="post" action="{{ route('subcategories.update', $subCategory->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Category Name:</label>
                    <select class="form-control" name="category_name" id="cat_id" required>
                        <option value="">-- Select Category --</option>
                        @foreach ($categories as $category)
                            <option
                                {{ $category->id === $subCategory->cat_id ? 'selected': ''}} value="{{ $category->id }}" {{ !$category->active ? 'disabled' : ''}}>
                                {{ $category->name }}
                            </option>
                        @endforeach
                    </select>

                </div>

                <div class="form-group">
                    <label for="name">Sub Category Name:</label>

                    <input type="text" class="form-control" name="subCategory_name" value="{{ $subCategory->subcat }}"/>
                </div>

                <div class="form-group">
                    <label for="active">Status</label>
                    <select class="form-control" id="active" name="active">
                        <option value="1" {{ $subCategory->active == 1 ? 'selected' : '' }}>Active</option>
                        <option value="0" {{ $subCategory->active == 0 ? 'selected' : '' }}>Inactive</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/subcategories/index.blade.php
@extends('layouts.app')

@section('title', 'Sub Category')

@section('content')
<h3>
    List of Sub categories
    <button type="button" class="btn btn-secondary ml-5" data-toggle="modal" data-target="#addContainerModel">
        Add New Sub Category
    </button>
</h3>
<div class="col-xs-12 filters">
    <a class="btn btn-sm btn-outline-success" href="/subcategories">Reset list</a>
    <a class="btn btn-sm btn-outline-info" href="/subcategories?select_inactive=true">Show Inactive</a>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Main Category</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($subcategories as $subcategory)
        <tr class="{{ $subcategory->active == 0 ? 'text-danger' : '' }}">
            <td>{{ $subcategory->id }}</td>
            <td>{{ $subcategory->subcat }}</td>
            <td>
                <a href="/categories/{{ $subcategory->category->id }}">{{ $subcategory->category->name }}</a>
                <label class="text-danger">{{ !$subcategory->category->active ? ' (Inactive)' : ''}}</label>
            </td>
            <td>
                <a href="/subcategories/{{ $subcategory->id}}" class="btn btn-secondary">View</a>
                <a href="/subcategories/{{ $subcategory->id}}/edit" class="btn btn-primary">Edit</a>
                {{--<a href="#" class="btn btn-danger" onclick="--}}
                    {{--var result = confirm('Are you sure you wish to DELETE {{ $subcategory->name }}?');--}}
                    {{--if (result){--}}
                        {{--event.preventDefault();--}}
                        {{--$('#delete-{{ $subcategory->id }}').submit();--}}
                    {{--}">Delete</a>--}}
                {{--<form id="delete-{{ $subcategory->id }}" action="{{ route('subcategories.destroy', $subcategory->id)}}"--}}
                    {{--method="POST" style="display:none">--}}
                    {{--@csrf--}}
                    {{--@method('DELETE')--}}
                    {{--<input value="delete" name="_method" type="hidden">--}}
                {{--</form>--}}
            </td>
        </tr>
        @endforeach

    </tbody>
</table>

<div class="modal fade" id="addContainerModel" tabindex="-1" role="dialog"
     aria-labelledby="addContainerModelTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ route('subcategories.store') }}">
                <div class="modal-header">
                    <h5 class="modal-title" id="addContainerModelLongTitle">Add New Sub Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Main Category:</label>
                        <select class="form-control" name="cat_id" id="cat_id" required>
                            <option value="">-- Select Category --</option>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="sub_category_name" required placeholder="Sub Category Name" />
                    </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/subcategories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-dark">Sub Category: {{ $sub_category->subcat }}</a>
    @foreach ($sub_category->items as $item)
    <a href="#" class="list-group-item list-group-item-action">
        {{ $item->item_code }} - {{ $item->item_name }}
        <span class="float-right">{{ $item->active == 1 ? 'Active' : 'Inactive' }}</span>
    </a>
    @endforeach
</div>

@endsection