routes/web.php
    Route::get('/growthstocks/print_bulk_number/{bulk_number}', 'GrowthRoomStockController@printBulkNumber');

    // Initiation Stock
    Route::get('/initiations/create', 'InitiationController@create')->name('initiations.create');
    Route::get('/initiations/growth_room', 'InitiationController@growthRoom')->name('initiations.growth');
    Route::get('/initiations/transfer_room', 'InitiationController@transferRoom')->name('initiations.transfer');
    Route::get('/initiations/to_transfer_room/{id}', 'InitiationController@toTransferRoom')->name('initiations.transfer_move');
    Route::get('/initiations/to_growth_room/{id}', 'InitiationController@toGrowthRoom')->name('initiations.growth_move');
    Route::get('/initiations/to_prod_transfer_room/{id}', 'InitiationController@toProdTransferRoom')->name('initiations.prod_transfer_move');
    Route::get('/initiations/to_rnd_transfer_room/{id}', 'InitiationController@toRndTransferRoom')->name('initiations.rnd_transfer_move');
    Route::post('/initiations/store', 'InitiationController@store')->name('initiations.store');


    // reports
    Route::get('/reports/performance', 'ReportsController@performance')->name('performance');
    Route::post('/reports/performance', 'ReportsController@performance')->name('reports.filter');
    Route::get('/reports/room_conditions', 'ReportsController@room_conditions')->name('room_conditions');
    Route::get('/reports/customer_reports/{id}', 'ReportsController@customerReports')->name('customer_reports');
    Route::get('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status');
    Route::post('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status.filter');
    Route::get('/reports/bulk_status/', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/bulk_status/{status}', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status');
    Route::post('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status.filter');

    Route::get('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock');
    Route::post('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock.filter');
    Route::get('/reports/week_bulk/{plant_id}/{year}/{week}/{media_id?}/{plant_size?}/', 'ReportsController@weekBulk')->name('weekBulk');

    Route::post('/reports/achievement', 'ReportsController@achievement')->name('operator.achievement');

    // Performance Breakdown
    Route::get('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd');
    Route::post('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd.filter');

    // Contamination Report
    Route::get('/reports/contamination', 'ReportsController@contamination')->name('contamination');
    Route::post('/reports/contamination', 'ReportsController@contamination')->name('contamination.filter');

    // Cutters performance
    Route::get('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');
    Route::post('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');

    // Visualization
    Route::resource('visualization', 'VisualizationController');
    Route::post('visualization/index', 'VisualizationController@index')->name('visualization.filter');
    Route::get('visualization/show', 'VisualizationController@show')->name('visualization.sales');
    Route::post('visualization/show', 'VisualizationController@show')->name('visualization.sales.filter');
    //tasks
    Route::get('/tasks/mark_completed/{id}', 'TaskController@mark_completed')->name('tasks.mark_completed');

    //orders
    Route::delete('/orders/destroy_order_item/{id}', 'OrderController@destroyOrderItem')->name('orders.destroy_order_item');
    Route::post('/orders/store_order_item', 'OrderController@storeOrderItems')->name('orders.store_order_item');


    // backend
    Route::get('/backend/find_bulk_number', 'BackEndController@findBulkNumber');
    Route::post('/backend/find_bulk_number', 'BackEndController@findBulkNumber')->name('findBulkNumber');
    Route::post('/backend/update_bulk_number', 'BackEndController@updateBulkNumber')->name('updateBulkNumber');
    Route::post('/backend/update_bulk_completed', 'BackEndController@updateBulkCompleted')->name('updateBulkCompleted');
    Route::get('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('setCustomersToPlant');
    Route::post('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('storeCustomersToPlant');
    Route::post('/backend/transfer_bulk', 'BackEndController@transferBulk')->name('transferBulk');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

    Route::get('/backend/find_media', 'BackEndController@findMedia');
    Route::get('/backend/get_media_plant_contamination/{media_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getMediaPlantContamination')->name('mediaPlantContamination');
    Route::post('/backend/find_media', 'BackEndController@findMedia')->name('findMedia');

    Route::get('/backend/find_container', 'BackEndController@findContainer');
    Route::get('/backend/get_container_plant_contamination/{container_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getContainerPlantContamination')->name('containerPlantContamination');
    Route::post('/backend/find_container', 'BackEndController@findContainer')->name('findContainer');

    Route::get('/backend/{user_id}/set_relationships', 'BackEndController@setRelationships')->name('setRelationships');


    // download apk file
    Route::get('/backend/download/{file}', 'BackEndController@download')->name('download_apk');

    Route::delete('/backend/deleteBulk/', 'BackEndController@deleteBulk')->name('deleteBulk');
    Route::delete('/backend/deleteSerialNumber/', 'BackEndController@deleteSerialNumber')->name('deleteSerialNumber');

    // greenhouse
    Route::post('/greenhouses', 'GreenhouseController@index')->name('greenhouses.filter');
    Route::post('/greenhouses/store', 'GreenhouseController@store')->name('greenhouses.store');
    Route::post('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::post('/greenhouses/sold', 'GreenhouseController@sold')->name('greenhouses.sold');
    Route::post('/greenhouses/reserve_stock', 'GreenhouseController@reserveStock')->name('greenhouses.reserve_stock');
    Route::get('/greenhouses/{id}/reserve', 'GreenhouseController@reserve')->name('greenhouses.reserve');
    Route::get('/greenhouses', 'GreenhouseController@index')->name('greenhouses.index');
    Route::get('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::get('/greenhouses/{id}/sell', 'GreenhouseController@sell')->name('greenhouses.sell');
    Route::get('/greenhouses/{id}/cancel', 'GreenhouseController@cancel')->name('greenhouses.cancel');
    Route::get('/greenhouses/{id}/plant_create', 'GreenhouseController@plantCreate')->name('greenhouses.plant_create');
    Route::get('/greenhouses/show/{id}/{task_id}', 'GreenhouseController@show');
    Route::get('/greenhouses/plants/{id}', 'GreenhouseController@plants');

    //RetailCustomer
    Route::get('/retail_customers/{id}/print_address', 'RetailCustomerController@printAddress')->name('retail_customers.print_address');

    //SalesRecords
    Route::get('sales_records', 'SalesRecordController@index');
    Route::get('/sales_records/{invoice_number}/invoiceNumber', 'SalesRecordController@invoiceNumber')->name('invoiceNumber');

    // Label Printers
    Route::get('printers', 'PrinterController@index');
    Route::get('printers/{id}/edit', 'PrinterController@edit')->name('printer.edit');
    Route::post('printers/store', 'PrinterController@store')->name('printer.store');
    Route::patch('printers/update/{id}', 'PrinterController@update')->name('printer.update');

    // Media requests
    Route::get('media_requests/cancel/{id}', 'MediaRequestController@cancel')->name('media_requests.cancel');
    Route::get('media_requests/revert/{id}', 'MediaRequestController@revert')->name('media_requests.revert');

    Route::resource('shares', 'ShareController');
    Route::resource('medias', 'MediaController');
    Route::resource('mediastocks', 'MediaStockController');
    Route::resource('growthstocks', 'GrowthRoomStockController');
    Route::resource('categories', 'CategoryController');
    Route::resource('reasons', 'ReasonController');
    Route::resource('subcategories', 'SubCategoryController');
    Route::resource('users', 'UserController');
    Route::resource('containers', 'ContainerController');
    Route::resource('items', 'ItemController');
    Route::resource('frequencies', 'FrequencyController');
    Route::resource('tasks', 'TaskController');
    Route::resource('companies', 'CompanyController');
    Route::resource('customers', 'CustomerController');
    Route::resource('retail_customers', 'RetailCustomerController');
    Route::resource('sales_records', 'SalesRecordController');
    Route::resource('orders', 'OrderController');
    Route::resource('greenhouses', 'GreenhouseController', ['except' => ['store']]);
    Route::resource('roles', 'RoleController');
    Route::resource('media_requests', 'MediaRequestController');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('media/autocomplete', 'MediaController@autocomplete')->name('media.autocomplete');
Route::get('item/autocomplete', 'ItemController@autocomplete')->name('item.autocomplete');
Route::get('sales/autocomplete', 'SalesRecordController@autocomplete')->name('sales.autocomplete');

app/Reason.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reason extends Model
{
    // protected $table = 'sub_cat';
    public $timestamps = false;

    protected $table = 'reasons';

    protected $fillable = ['name'];
}

app/Http/Controllers/ReasonController.php
<?php

namespace App\Http\Controllers;

use App\Reason;
use Illuminate\Http\Request;

class ReasonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reasons = Reason::get();
        return view('reasons.index', ['reasons' => $reasons]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'reason_name'=>'required'
        ]);
        $reason = new Reason([
            'name' => $request->get('reason_name')
        ]);
        if ($reason->save()){
            return redirect('/reasons')->with('success', 'New reason has been added');
        }
        return back()->withInput()->with('error', 'Coud not add reason');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Reason  $reason
     * @return \Illuminate\Http\Response
     */
    public function show(Reason $reason)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Reason  $reason
     * @return \Illuminate\Http\Response
     */
    public function edit(Reason $reason)
    {
        $reason = Reason::find($reason->id);

        return view('reasons.edit', compact('reason'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Reason  $reason
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $reason)
    {
        $request->validate([
            'reason_name'=>'required',

        ]);

        $reason = Reason::find($reason);
        $reason->name = $request->get('reason_name');
        $reason->save();

        return redirect('/reasons')->with('success', 'Reason has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Reason  $reason
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reason $reason)
    {
        $reason = Reason::find($reason->id);
        if ($reason->delete()){
            return redirect('/reasons')->with('success', 'Reason has been deleted Successfully');
        }
        return back()->withInput()->with('error', 'Reason coud not be deleted');
    }
}

resources/views/reasons/edit.blade.php
@extends('layouts.app')

@section('content')

    <style>
        .uper {
            margin-top: 40px;
        }
    </style>
    <div class="card uper">
        <div class="card-header">
            Edit Reason
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('reasons.update', $reason->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Reason Name:</label>
                    <input type="text" class="form-control" name="reason_name" value="{{ $reason->name }}" />
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
    
@endsection

resources/views/reasons/index.blade.php
@extends('layouts.app')

@section('content')
<div id="add_reason" style="display:none">
    <h3 class="display-5">
        Add Reason
    </h3>
    <form method="POST" action="{{ route('reasons.store') }}">
        <div class="form-group">
            {{ csrf_field() }}
            <input type="text" class="form-control" name="reason_name" required placeholder="Reason Name"
                minlength="3" />
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>
    <hr />
</div>

<h3>
    List of Reasons
    <button type="button" class="btn btn-secondary ml-5" data-toggle="modal" data-target="#addContainerModel">
        Add New Reason
    </button>
</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($reasons as $reason)
        <tr>
            <td>{{ $reason->name }}</td>
            <td>
                <a href="/reasons/{{ $reason->id}}/edit" class="btn btn-primary">Edit</a>
                {{--<a href="#" class="btn btn-danger" onclick="--}}
                    {{--var result = confirm('Are you sure you wish to DELETE {{ $reason->name }}?');--}}
                    {{--if (result){--}}
                        {{--event.preventDefault();--}}
                                   {{--$('#delete-{{ $reason->id }}').submit();--}}
                    {{--}">Delete</a>--}}
                {{--<form id="delete-{{ $reason->id }}" action="{{ route('reasons.destroy', $reason->id)}}" method="POST"--}}
                    {{--style="display:none">--}}
                    {{--@csrf--}}
                    {{--@method('DELETE')--}}
                    {{--<input value="delete" name="_method" type="hidden">--}}
                {{--</form>--}}
            </td>
        </tr>
        @endforeach

    </tbody>
</table>

<div class="modal fade" id="addContainerModel" tabindex="-1" role="dialog"
     aria-labelledby="addContainerModelTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ route('reasons.store') }}">
                <div class="modal-header">
                    <h5 class="modal-title" id="addContainerModelLongTitle">Add Reason</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <input type="text" class="form-control" name="reason_name" id="reason_name" required placeholder="Reason Name" minlength="3" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $('#addContainerModel').on('shown.bs.modal', function() {
        $('#reason_name').focus();
    })
</script>

@endsection