routes/web.php
    Route::get('/growthstocks/print_bulk_number/{bulk_number}', 'GrowthRoomStockController@printBulkNumber');

    // Initiation Stock
    Route::get('/initiations/create', 'InitiationController@create')->name('initiations.create');
    Route::get('/initiations/growth_room', 'InitiationController@growthRoom')->name('initiations.growth');
    Route::get('/initiations/transfer_room', 'InitiationController@transferRoom')->name('initiations.transfer');
    Route::get('/initiations/to_transfer_room/{id}', 'InitiationController@toTransferRoom')->name('initiations.transfer_move');
    Route::get('/initiations/to_growth_room/{id}', 'InitiationController@toGrowthRoom')->name('initiations.growth_move');
    Route::get('/initiations/to_prod_transfer_room/{id}', 'InitiationController@toProdTransferRoom')->name('initiations.prod_transfer_move');
    Route::get('/initiations/to_rnd_transfer_room/{id}', 'InitiationController@toRndTransferRoom')->name('initiations.rnd_transfer_move');
    Route::post('/initiations/store', 'InitiationController@store')->name('initiations.store');


    // reports
    Route::get('/reports/performance', 'ReportsController@performance')->name('performance');
    Route::post('/reports/performance', 'ReportsController@performance')->name('reports.filter');
    Route::get('/reports/room_conditions', 'ReportsController@room_conditions')->name('room_conditions');
    Route::get('/reports/customer_reports/{id}', 'ReportsController@customerReports')->name('customer_reports');
    Route::get('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status');
    Route::post('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status.filter');
    Route::get('/reports/bulk_status/', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/bulk_status/{status}', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status');
    Route::post('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status.filter');

    Route::get('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock');
    Route::post('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock.filter');
    Route::get('/reports/week_bulk/{plant_id}/{year}/{week}/{media_id?}/{plant_size?}/', 'ReportsController@weekBulk')->name('weekBulk');

    Route::post('/reports/achievement', 'ReportsController@achievement')->name('operator.achievement');

    // Performance Breakdown
    Route::get('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd');
    Route::post('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd.filter');

    // Contamination Report
    Route::get('/reports/contamination', 'ReportsController@contamination')->name('contamination');
    Route::post('/reports/contamination', 'ReportsController@contamination')->name('contamination.filter');

    // Cutters performance
    Route::get('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');
    Route::post('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');

    // Visualization
    Route::resource('visualization', 'VisualizationController');
    Route::post('visualization/index', 'VisualizationController@index')->name('visualization.filter');
    Route::get('visualization/show', 'VisualizationController@show')->name('visualization.sales');
    Route::post('visualization/show', 'VisualizationController@show')->name('visualization.sales.filter');
    //tasks
    Route::get('/tasks/mark_completed/{id}', 'TaskController@mark_completed')->name('tasks.mark_completed');

    //orders
    Route::delete('/orders/destroy_order_item/{id}', 'OrderController@destroyOrderItem')->name('orders.destroy_order_item');
    Route::post('/orders/store_order_item', 'OrderController@storeOrderItems')->name('orders.store_order_item');


    // backend
    Route::get('/backend/find_bulk_number', 'BackEndController@findBulkNumber');
    Route::post('/backend/find_bulk_number', 'BackEndController@findBulkNumber')->name('findBulkNumber');
    Route::post('/backend/update_bulk_number', 'BackEndController@updateBulkNumber')->name('updateBulkNumber');
    Route::post('/backend/update_bulk_completed', 'BackEndController@updateBulkCompleted')->name('updateBulkCompleted');
    Route::get('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('setCustomersToPlant');
    Route::post('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('storeCustomersToPlant');
    Route::post('/backend/transfer_bulk', 'BackEndController@transferBulk')->name('transferBulk');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

    Route::get('/backend/find_media', 'BackEndController@findMedia');
    Route::get('/backend/get_media_plant_contamination/{media_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getMediaPlantContamination')->name('mediaPlantContamination');
    Route::post('/backend/find_media', 'BackEndController@findMedia')->name('findMedia');

    Route::get('/backend/find_container', 'BackEndController@findContainer');
    Route::get('/backend/get_container_plant_contamination/{container_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getContainerPlantContamination')->name('containerPlantContamination');
    Route::post('/backend/find_container', 'BackEndController@findContainer')->name('findContainer');

    Route::get('/backend/{user_id}/set_relationships', 'BackEndController@setRelationships')->name('setRelationships');


    // download apk file
    Route::get('/backend/download/{file}', 'BackEndController@download')->name('download_apk');

    Route::delete('/backend/deleteBulk/', 'BackEndController@deleteBulk')->name('deleteBulk');
    Route::delete('/backend/deleteSerialNumber/', 'BackEndController@deleteSerialNumber')->name('deleteSerialNumber');

    // greenhouse
    Route::post('/greenhouses', 'GreenhouseController@index')->name('greenhouses.filter');
    Route::post('/greenhouses/store', 'GreenhouseController@store')->name('greenhouses.store');
    Route::post('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::post('/greenhouses/sold', 'GreenhouseController@sold')->name('greenhouses.sold');
    Route::post('/greenhouses/reserve_stock', 'GreenhouseController@reserveStock')->name('greenhouses.reserve_stock');
    Route::get('/greenhouses/{id}/reserve', 'GreenhouseController@reserve')->name('greenhouses.reserve');
    Route::get('/greenhouses', 'GreenhouseController@index')->name('greenhouses.index');
    Route::get('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::get('/greenhouses/{id}/sell', 'GreenhouseController@sell')->name('greenhouses.sell');
    Route::get('/greenhouses/{id}/cancel', 'GreenhouseController@cancel')->name('greenhouses.cancel');
    Route::get('/greenhouses/{id}/plant_create', 'GreenhouseController@plantCreate')->name('greenhouses.plant_create');
    Route::get('/greenhouses/show/{id}/{task_id}', 'GreenhouseController@show');
    Route::get('/greenhouses/plants/{id}', 'GreenhouseController@plants');

    //RetailCustomer
    Route::get('/retail_customers/{id}/print_address', 'RetailCustomerController@printAddress')->name('retail_customers.print_address');

    //SalesRecords
    Route::get('sales_records', 'SalesRecordController@index');
    Route::get('/sales_records/{invoice_number}/invoiceNumber', 'SalesRecordController@invoiceNumber')->name('invoiceNumber');

    // Label Printers
    Route::get('printers', 'PrinterController@index');
    Route::get('printers/{id}/edit', 'PrinterController@edit')->name('printer.edit');
    Route::post('printers/store', 'PrinterController@store')->name('printer.store');
    Route::patch('printers/update/{id}', 'PrinterController@update')->name('printer.update');

    // Media requests
    Route::get('media_requests/cancel/{id}', 'MediaRequestController@cancel')->name('media_requests.cancel');
    Route::get('media_requests/revert/{id}', 'MediaRequestController@revert')->name('media_requests.revert');

    Route::resource('shares', 'ShareController');
    Route::resource('medias', 'MediaController');
    Route::resource('mediastocks', 'MediaStockController');
    Route::resource('growthstocks', 'GrowthRoomStockController');
    Route::resource('categories', 'CategoryController');
    Route::resource('reasons', 'ReasonController');
    Route::resource('subcategories', 'SubCategoryController');
    Route::resource('users', 'UserController');
    Route::resource('containers', 'ContainerController');
    Route::resource('items', 'ItemController');
    Route::resource('frequencies', 'FrequencyController');
    Route::resource('tasks', 'TaskController');
    Route::resource('companies', 'CompanyController');
    Route::resource('customers', 'CustomerController');
    Route::resource('retail_customers', 'RetailCustomerController');
    Route::resource('sales_records', 'SalesRecordController');
    Route::resource('orders', 'OrderController');
    Route::resource('greenhouses', 'GreenhouseController', ['except' => ['store']]);
    Route::resource('roles', 'RoleController');
    Route::resource('media_requests', 'MediaRequestController');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('media/autocomplete', 'MediaController@autocomplete')->name('media.autocomplete');
Route::get('item/autocomplete', 'ItemController@autocomplete')->name('item.autocomplete');
Route::get('sales/autocomplete', 'SalesRecordController@autocomplete')->name('sales.autocomplete');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'user_id',
        'description',
        'date_started',
        'date_completed',
        'frequency_id',
        'is_complete'
    ];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function frequency()
    {
        return $this->belongsTo('App\Frequency', 'frequency_id');
    }

}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Frequency;
use App\User;
use App\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Auth;
use phpDocumentor\Reflection\Types\Self_;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Input;


class TaskController extends Controller
{
    public function index()
    {
        $tasks = Task::all();
        return view('tasks.index', compact('tasks'));
    }

    public function create()
    {
        $admin_user = auth()->user()->hasRole('Administrator');
        if (!$admin_user) {
            $role = 'Operator';
            $users = User::whereHas('roles', function ($q) use ($role) {
                $q->where('name', '=', $role);
            })->where([['active', '=', '1'], ['user_code', 'NOT LIKE', 'CUS_%']])->pluck('name', 'id');
        } else {
            $users = User::where([['active', '=', '1'], ['user_code', 'NOT LIKE', 'CUS_%']])->pluck('name', 'id');
        }
        $frequencies = Frequency::all()->pluck('frequency', 'id');
        return view('tasks.create', compact('users', 'frequencies'));
    }

    public function store(Request $request)
    {
        //dd(date("Y-m-d H:i:s", strtotime($request->get('start_date'))));
        $request->validate([
            'user_id' => 'required',
            'description' => 'required|string',
            'freq' => 'required',
            'start_date' => 'required',
            'end_date' => 'required'
        ]);
        $task = new Task([
            'user_id' => $request->get('user_id'),
            'description' => $request->get('description'),
            'frequency_id' => $request->get('freq'),
            'date_started' => date("Y-m-d H:i:s", strtotime($request->get('start_date'))),
            'date_completed' => date("Y-m-d H:i:s", strtotime($request->get('end_date'))),
        ]);
        $task->save();

        return redirect('/tasks')->with('success', 'Task has been added');
    }

    public function edit($id)
    {
        $task = Task::find($id);

        $admin_user = auth()->user()->hasRole('Administrator');
        if (!$admin_user) {
            $role = 'Operator';
            $users = User::whereHas('roles', function ($q) use ($role) {
                $q->where('name', '=', $role);
            })->where([['active', '=', '1'], ['user_code', 'NOT LIKE', 'CUS_%']])->pluck('name', 'id');
        } else {
            $users = User::where([['active', '=', '1'], ['user_code', 'NOT LIKE', 'CUS_%']])->pluck('name', 'id');
        }

        $frequencies = Frequency::all()->pluck('frequency', 'id');

        return view('tasks.edit', compact('task', 'users', 'frequencies'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'user_id' => 'required',
            'description' => 'required|string',
            'frequency_id' => 'required',
            'start_date' => 'required',
            'end_date' => 'required'
        ]);

        $task = Task::find($id);
        $task->user_id = $request->get('user_id');
        $task->description = $request->get('description');
        $task->frequency_id = $request->get('frequency_id');
        $task->date_started = date("Y-m-d H:i:s", strtotime($request->get('start_date')));
        $task->date_completed = date("Y-m-d H:i:s", strtotime($request->get('end_date')));
        $task->is_complete = $request->get('is_complete');
        $task->save();

        return redirect('/tasks')->with('success', 'Task has been updated');
    }

    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();

        return redirect('/tasks')->with('success', 'Task has been deleted Successfully');
    }

    public function mark_completed($id)
    {
        $task = Task::find($id);
        $task->is_complete = 1;
        $task->save();
        return redirect('/tasks')->with('success', 'Task has been makred as Completed!!');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
<script type='text/javascript'>
    $(document).ready(function(){

    //     $( function() {
    //         $( " #start_date" ).datepicker( {dateFormat: 'yy-mm-dd' }, ).attr('readonly','readonly'); $( "#end_date"
    // ).datepicker( {dateFormat: 'yy-mm-dd' }, ).attr('readonly','readonly'); } ); }); 

    $('#start_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'green',auto: true, rangeTo: '#end_date'});
    $('#end_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'green',auto: true, rangeFrom: '#start_date'});

    });
</script>
<div class="container">
    <div class="card">
        <div class="card-header">
            Add Task
        </div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <form method="post" action="{{ route('tasks.store') }}">
                <div class="form-group">
                    <label for="name">Operator Name:</label>
                    <select class="form-control" name="user_id" id="user_id" required>
                        <option>Select User</option>
                        @foreach ($users as $key => $value)
                        <option value="{{ $key }}">
                            {{ $value }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="price">Description :</label>
                    <textarea name="description" class="form-control" id="description"></textarea>
                </div>
                <div class="form-group">
                    <label for="name">Frequency:</label>
                    <select class="form-control" name="freq" id="freq" required>
                        <option>Select Frequency</option>
                        @foreach ($frequencies as $key => $value)
                        <option value="{{ $key }}">
                            {{ $value }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Start Date:</label>
                    <input type="text" class="form-control" name="start_date" id="start_date" required
                        data-rangeto="#end_date" />
                </div>
                <div class="form-group">
                    <label for="name">End Date:</label>
                    <input type="text" class="form-control" name="end_date" id="end_date" required
                        data-rangefrom="#start_date" />
                </div>
                <button type="submit" class="btn btn-primary">Add Task</button>
                {{ csrf_field() }}
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
<script type='text/javascript'>
    $(document).ready(function(){
        $('#start_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'green',auto: true, rangeTo: '#end_date'});
        $('#end_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'green',auto: true, rangeFrom: '#start_date'});
    });
</script>

<div class="container">
    <div class="card">
        <div class="card-header">
            Update Task
        </div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <form method="post" action="{{ route('tasks.update', $task->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Operator Name:</label>
                    <select class="form-control" name="user_id" id="user_id" required>
                        <option>Select User</option>
                        @foreach ($users as $key => $value)
                        <option value="{{ $key }}" {{ $key == $task->user_id ? 'selected' : '' }}>
                            {{ $value }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="price">Description :</label>
                    <textarea name="description" class="form-control"
                        id="description">{{ $task->description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="name">Frequency:</label>
                    <select class="form-control" name="frequency_id" id="frequency_id" required>
                        <option>Select Frequency</option>
                        @foreach ($frequencies as $key => $value)
                        <option value="{{ $key }}" {{ $key == $task->frequency_id ? 'selected' : '' }}>
                            {{ $value }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Start Date:</label>
                    <input type="text" class="form-control" name="start_date" id="start_date" required
                        data-rangeto="#end_date" value={{ $task->date_started }} />
                </div>
                <div class="form-group">
                    <label for="name">End Date:</label>
                    <input type="text" class="form-control" name="end_date" id="end_date" required
                        data-rangefrom="#start_date" value={{ $task->date_completed }} />
                </div>
                <div class="form-group">
                    <label for="name">Status:</label>
                    @php
                    $status = [0 => 'Pending', 1 => 'Done'];
                    @endphp
                    <select class="form-control" name="is_complete" id="is_complete">
                        @foreach ($status as $key => $value)
                        <option value="{{ $key }}" {{ $key == $task->is_complete ? 'selected' : '' }}>
                            {{ $value }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Update Task</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')

<div>
    <h2>Tasks</h2>
    <table class="table table-striped" id="mediaStocks">
        <thead>
            <tr>
                <th>Operator</th>
                <th>Description</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Frequency</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tasks as $task)
            <tr>
                <td>{{$task->user->name}}</td>
                <td>{{$task->description}}</td>
                <td>{{ date('Y-m-d', strtotime($task->date_started))}}</td>
                <td>{{date('Y-m-d', strtotime($task->date_completed))}}</td>
                <td>{{$task->frequency->frequency ?? ''}}</td>
                @php
                $start = date_create(date("Y-m-d"));
                $end = date_create(date('Y-m-d', strtotime($task->date_completed)));
                $diff=date_diff($start,$end);
                @endphp
                <td>{{($task->is_complete ==1 )? "Done":"Pending ".$diff->format("%R%a days") }}
                </td>
                <td>
                    <a href="{{ route('tasks.edit', $task->id)}}" class="btn btn-primary">
                        <i class="far fa-edit"></i> Edit
                    </a>

                    @if ($task->is_complete !== 1)
                    <a href="{{ route('tasks.mark_completed', $task->id)}}" class="btn btn-success">
                        <i class="far fa-calendar-check"></i> Mark As Complete
                    </a>
                    @endif

                    @if(Auth::user()->hasRole('Administrator'))
                    <form action="{{ route('tasks.destroy', $task->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger float-left mt-2" type="submit">
                            <i class="far fa-trash-alt"></i> Delete
                        </button>
                    </form>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{-- {{ $mediastocks->onEachSide(1)->links() }} --}}
</div>
<style>
    .dataTables_filter input[type="search"] {
        border: 1px solid #ced4da;
        border-radius: .25rem;
        padding: 2px;
    }
</style>
@endsection