routes/web.php
    Route::get('/growthstocks/print_bulk_number/{bulk_number}', 'GrowthRoomStockController@printBulkNumber');

    // Initiation Stock
    Route::get('/initiations/create', 'InitiationController@create')->name('initiations.create');
    Route::get('/initiations/growth_room', 'InitiationController@growthRoom')->name('initiations.growth');
    Route::get('/initiations/transfer_room', 'InitiationController@transferRoom')->name('initiations.transfer');
    Route::get('/initiations/to_transfer_room/{id}', 'InitiationController@toTransferRoom')->name('initiations.transfer_move');
    Route::get('/initiations/to_growth_room/{id}', 'InitiationController@toGrowthRoom')->name('initiations.growth_move');
    Route::get('/initiations/to_prod_transfer_room/{id}', 'InitiationController@toProdTransferRoom')->name('initiations.prod_transfer_move');
    Route::get('/initiations/to_rnd_transfer_room/{id}', 'InitiationController@toRndTransferRoom')->name('initiations.rnd_transfer_move');
    Route::post('/initiations/store', 'InitiationController@store')->name('initiations.store');


    // reports
    Route::get('/reports/performance', 'ReportsController@performance')->name('performance');
    Route::post('/reports/performance', 'ReportsController@performance')->name('reports.filter');
    Route::get('/reports/room_conditions', 'ReportsController@room_conditions')->name('room_conditions');
    Route::get('/reports/customer_reports/{id}', 'ReportsController@customerReports')->name('customer_reports');
    Route::get('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status');
    Route::post('/reports/plant_status', 'ReportsController@plantStatus')->name('plant_status.filter');
    Route::get('/reports/bulk_status/', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/bulk_status/{status}', 'ReportsController@setBulkStatus')->name('bulk_status');
    Route::get('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status');
    Route::post('/reports/plants_media_status', 'ReportsController@plantsMediaStatus')->name('plants_media_status.filter');

    Route::get('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock');
    Route::post('/reports/plant_stock', 'ReportsController@PlantStock')->name('plant_stock.filter');
    Route::get('/reports/week_bulk/{plant_id}/{year}/{week}/{media_id?}/{plant_size?}/', 'ReportsController@weekBulk')->name('weekBulk');

    Route::post('/reports/achievement', 'ReportsController@achievement')->name('operator.achievement');

    // Performance Breakdown
    Route::get('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd');
    Route::post('/reports/performance_breakdown', 'ReportsController@performanceBreakdown')->name('performance.bd.filter');

    // Contamination Report
    Route::get('/reports/contamination', 'ReportsController@contamination')->name('contamination');
    Route::post('/reports/contamination', 'ReportsController@contamination')->name('contamination.filter');

    // Cutters performance
    Route::get('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');
    Route::post('/reports/cutters_performance', 'ReportsController@cuttersPerformance')->name('cutters.performance');

    // Visualization
    Route::resource('visualization', 'VisualizationController');
    Route::post('visualization/index', 'VisualizationController@index')->name('visualization.filter');
    Route::get('visualization/show', 'VisualizationController@show')->name('visualization.sales');
    Route::post('visualization/show', 'VisualizationController@show')->name('visualization.sales.filter');
    //tasks
    Route::get('/tasks/mark_completed/{id}', 'TaskController@mark_completed')->name('tasks.mark_completed');

    //orders
    Route::delete('/orders/destroy_order_item/{id}', 'OrderController@destroyOrderItem')->name('orders.destroy_order_item');
    Route::post('/orders/store_order_item', 'OrderController@storeOrderItems')->name('orders.store_order_item');


    // backend
    Route::get('/backend/find_bulk_number', 'BackEndController@findBulkNumber');
    Route::post('/backend/find_bulk_number', 'BackEndController@findBulkNumber')->name('findBulkNumber');
    Route::post('/backend/update_bulk_number', 'BackEndController@updateBulkNumber')->name('updateBulkNumber');
    Route::post('/backend/update_bulk_completed', 'BackEndController@updateBulkCompleted')->name('updateBulkCompleted');
    Route::get('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('setCustomersToPlant');
    Route::post('/backend/set_customer_to_plant', 'BackEndController@setCustomersToPlant')->name('storeCustomersToPlant');
    Route::post('/backend/transfer_bulk', 'BackEndController@transferBulk')->name('transferBulk');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

    Route::get('/backend/find_media', 'BackEndController@findMedia');
    Route::get('/backend/get_media_plant_contamination/{media_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getMediaPlantContamination')->name('mediaPlantContamination');
    Route::post('/backend/find_media', 'BackEndController@findMedia')->name('findMedia');

    Route::get('/backend/find_container', 'BackEndController@findContainer');
    Route::get('/backend/get_container_plant_contamination/{container_id?}/{plant_id?}/{year}/{week}/', 'BackEndController@getContainerPlantContamination')->name('containerPlantContamination');
    Route::post('/backend/find_container', 'BackEndController@findContainer')->name('findContainer');

    Route::get('/backend/{user_id}/set_relationships', 'BackEndController@setRelationships')->name('setRelationships');


    // download apk file
    Route::get('/backend/download/{file}', 'BackEndController@download')->name('download_apk');

    Route::delete('/backend/deleteBulk/', 'BackEndController@deleteBulk')->name('deleteBulk');
    Route::delete('/backend/deleteSerialNumber/', 'BackEndController@deleteSerialNumber')->name('deleteSerialNumber');

    // greenhouse
    Route::post('/greenhouses', 'GreenhouseController@index')->name('greenhouses.filter');
    Route::post('/greenhouses/store', 'GreenhouseController@store')->name('greenhouses.store');
    Route::post('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::post('/greenhouses/sold', 'GreenhouseController@sold')->name('greenhouses.sold');
    Route::post('/greenhouses/reserve_stock', 'GreenhouseController@reserveStock')->name('greenhouses.reserve_stock');
    Route::get('/greenhouses/{id}/reserve', 'GreenhouseController@reserve')->name('greenhouses.reserve');
    Route::get('/greenhouses', 'GreenhouseController@index')->name('greenhouses.index');
    Route::get('/greenhouses/plant_stock', 'GreenhouseController@plantStock')->name('greenhouses.plant_stock');
    Route::get('/greenhouses/{id}/sell', 'GreenhouseController@sell')->name('greenhouses.sell');
    Route::get('/greenhouses/{id}/cancel', 'GreenhouseController@cancel')->name('greenhouses.cancel');
    Route::get('/greenhouses/{id}/plant_create', 'GreenhouseController@plantCreate')->name('greenhouses.plant_create');
    Route::get('/greenhouses/show/{id}/{task_id}', 'GreenhouseController@show');
    Route::get('/greenhouses/plants/{id}', 'GreenhouseController@plants');

    //RetailCustomer
    Route::get('/retail_customers/{id}/print_address', 'RetailCustomerController@printAddress')->name('retail_customers.print_address');

    //SalesRecords
    Route::get('sales_records', 'SalesRecordController@index');
    Route::get('/sales_records/{invoice_number}/invoiceNumber', 'SalesRecordController@invoiceNumber')->name('invoiceNumber');

    // Label Printers
    Route::get('printers', 'PrinterController@index');
    Route::get('printers/{id}/edit', 'PrinterController@edit')->name('printer.edit');
    Route::post('printers/store', 'PrinterController@store')->name('printer.store');
    Route::patch('printers/update/{id}', 'PrinterController@update')->name('printer.update');

    // Media requests
    Route::get('media_requests/cancel/{id}', 'MediaRequestController@cancel')->name('media_requests.cancel');
    Route::get('media_requests/revert/{id}', 'MediaRequestController@revert')->name('media_requests.revert');

    Route::resource('shares', 'ShareController');
    Route::resource('medias', 'MediaController');
    Route::resource('mediastocks', 'MediaStockController');
    Route::resource('growthstocks', 'GrowthRoomStockController');
    Route::resource('categories', 'CategoryController');
    Route::resource('reasons', 'ReasonController');
    Route::resource('subcategories', 'SubCategoryController');
    Route::resource('users', 'UserController');
    Route::resource('containers', 'ContainerController');
    Route::resource('items', 'ItemController');
    Route::resource('frequencies', 'FrequencyController');
    Route::resource('tasks', 'TaskController');
    Route::resource('companies', 'CompanyController');
    Route::resource('customers', 'CustomerController');
    Route::resource('retail_customers', 'RetailCustomerController');
    Route::resource('sales_records', 'SalesRecordController');
    Route::resource('orders', 'OrderController');
    Route::resource('greenhouses', 'GreenhouseController', ['except' => ['store']]);
    Route::resource('roles', 'RoleController');
    Route::resource('media_requests', 'MediaRequestController');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('media/autocomplete', 'MediaController@autocomplete')->name('media.autocomplete');
Route::get('item/autocomplete', 'ItemController@autocomplete')->name('item.autocomplete');
Route::get('sales/autocomplete', 'SalesRecordController@autocomplete')->name('sales.autocomplete');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'customer_id',
        'order_date',
        'required_date',
        'shipped_date',
        'order_status',
        'user_id'
    ];

    public function customer()
    {
        return $this->belongsTo('App\Customer', 'customer_id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function order_items()
    {
        return $this->hasMany('App\OrderItem', 'order_id');
    }

    public function performance()
    {
        return $this->hasMany('App\Performance');
    }

    public function getOrderDateAttribute($value){
        return substr($value, 0, 10);
    }

    public function getRequiredDateAttribute($value){
        return substr($value, 0, 10);
    }

    public function getShippedDateAttribute($value){
        return substr($value, 0, 10);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\Customer;
use App\OrderItem;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();

        return view('orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::where('is_active', '=', 1)->get();
        return view('orders.create', compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'customer_id' => 'required',
            'order_date' => 'required',
            'required_date' => 'required'
        ]);

        $order = new Order();
        $order->customer_id     = $request->get('customer_id');
        $order->order_date      = $request->get('order_date');
        $order->required_date   = $request->get('required_date');
        $order->user_id         = Auth::id();
        $order->order_status    = 0;

        if ($order->save()) {
            return redirect('/orders/'.$order->id)->with('success', 'new order has been created');
        }

        return back()->withInput()->with('error', 'Could not create an order');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        return view('orders.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);
        $customers = Customer::where('is_active', '=', 1)->get();
        return view('orders.edit', compact('order','customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'customer_id' => 'required',
            'order_date' => 'required',
            'required_date' => 'required'
        ]);

        $order = Order::find($id);

        $order->customer_id     = $request->get('customer_id');
        $order->order_date      = $request->get('order_date');
        $order->required_date   = $request->get('required_date');
        $order->shipped_date    = $request->get('shipped_date');
        $order->order_status    = $request->get('order_status');

        if ($order->save()) {
            return redirect('/orders/'.$order->id)->with('success', 'Update order details');
        }

        return back()->withInput()->with('error', 'Could not update order');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = Order::find($id);
        if($order->performance->isEmpty()){
            $order->delete();
            OrderItem::where('order_id', '=', $order->id)->delete();
            return redirect('/orders')->with('success', 'Order has been removed successfully');
        }else {
            return redirect()->back()->with('error', 'This Order can\'t been deleted records exist in other tables');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroyOrderItem($id)
    {
        $order_item = OrderItem::find($id);
        $order_id = $order_item->order_id;
        $order_item->delete();

        return redirect()->back()->with('success', 'Item has been removed from the order successfully');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeOrderItems(Request $request)
    {
        $request->validate([
            'selected_order_id' => 'required',
            'selected_item_id' => 'required',
            'quantity' => 'required'
        ]);

        $order_item = new OrderItem();
        $order_item->order_id     = $request->get('selected_order_id');
        $order_item->item_id      = $request->get('selected_item_id');
        $order_item->quantity     = $request->get('quantity');

        if ($order_item->save()) {
            return redirect('/orders/'.$order_item->order_id)->with('success', 'new item has been added to the order');
        }

        return back()->withInput()->with('error', 'Could not add an item');
    }
}

resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')
<script>
    $(document).ready(function() {
        $( function() {
            $('#order_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'teal',auto: true, dOrder: '#date_ordered'});
            $('#required_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'blue',auto: true, dReq: '#date_required'});
        } );
    });
</script>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-8">
            <div class="card">
                <div class="card-header">
                    Create Order
                </div>
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                    @endif
                    <form method="post" action="{{ route('orders.store') }}">
                        @csrf
                        @method('POST')
                        <div class="form-group">
                            <label for="media_type">Customer :</label><br />
                            <select class="form-control" name="customer_id" id="customer_id" required>
                                <option value="">Select Customer</option>
                                @foreach ($customers as $key => $value)
                                <option value="{{ $value->id }}">
                                    {{ $value->name }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="name">Ordered date:</label>
                            <input type="text" class="form-control" name="order_date" id="order_date" autocomplete=“off”
                                data-dOrder="#date_ordered" required />
                        </div>

                        <div class="form-group">
                            <label for="name">Required date:</label>
                            <input type="text" class="form-control" name="required_date" id="required_date"
                                autocomplete=“off” data-dReq="#date_required" required />
                        </div>
                        <button type="submit" class="btn btn-primary mt-2">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
    <script>
        $(document).ready(function() {
            $( function() {
                $('#order_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'teal',auto: true, dOrder: '#date_ordered'});
                $('#required_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'blue',auto: true, dReq: '#date_required'});
                $('#shipped_date').duDatepicker({format: 'yyyy-mm-dd',theme: 'red',auto: true, dShip: '#date_shipped'});
            } );
        });
    </script>
<div class="card">
    <div class="card-header">
        Edit Order: {{ $order->id }}
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('orders.update', $order->id) }}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="media_type">Customer :</label><br />
                <select class="form-control" name="customer_id" id="customer_id" required>
                    <option value="">Select Customer</option>
                    @foreach ($customers as $customer)
                        <option {{ $customer->id == $order->customer_id  ? 'selected' : ''}} value="{{ $customer->id }}">
                            {{ $customer->name }}
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="name">Ordered date:</label>
                <input type="text" class="form-control" name="order_date" id="order_date" autocomplete=“off”
                       data-dOrder="#date_ordered" value="{{ $order->order_date }}" />
            </div>
            <div class="form-group">
                <label for="name">Required date:</label>
                <input type="text" class="form-control" name="required_date" id="required_date"
                       autocomplete=“off” data-dReq="#date_required" value="{{ $order->required_date }}" />
            </div>
            <div class="form-group">
                <label for="name">Required date:</label>
                <input type="text" class="form-control" name="shipped_date" id="shipped_date"
                       autocomplete=“off” data-dShip="#date_shipped" value="{{ $order->shipped_date }}" />
            </div>
            <div class="form-group">
                <label for="media_type">Order Status :</label><br />
                <select class="form-control" name="order_status" id="order_status">
                    <option value="">Change Status</option>
                    @foreach (config('app.order_status') as $key => $value)
                        <option {{ $key == $order->order_status  ? 'selected' : ''}} value="{{ $key }}">
                            {{ $value }}
                        </option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')

<h3>
    List of Orders
    <a href="{{ route('orders.create') }}" class="btn btn-secondary ml-5">Add New Order</a>
</h3>
<div class="uper">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Customer Name</th>
                <th>Order Date</th>
                <th>Required Date</th>
                <th>Order Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td>{{ $order->id }}</td>
                <td>{{ $order->customer->name }}</td>
                <td>{{ $order->order_date }}</td>
                <td>{{ $order->required_date }}</td>
                <td>{{ config('app.order_status')[$order->order_status] ?? '' }}</td>
                <td>
                    <a href="{{ route('orders.show',$order->id) }}" class="btn btn-primary">View</a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')

@section('content')
    <script src="{{ asset('js/bootstrap3-typeahead.min.js') }}"></script>
<div class="container">
    <div class="card uper">
        <div class="card-header">
            Order No: {{ $order->id }}
            <div class="btn-group float-right" role="group" aria-label="Basic example">
                <a href="{{ route('orders.edit',$order->id)}}" class="btn btn-info float-right btn-sm"><i class="far fa-edit"></i> Edit</a>
                <form action="{{ route('orders.destroy', $order->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm float-right" type="submit"><i class="far fa-trash-alt"></i></button>
                </form>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Customer Name</th>
                        <td>{{ $order->customer->name }}</td>
                    </tr>
                    <tr>
                        <th>Order Date</th>
                        <td>{{ $order->order_date }}</td>
                    </tr>
                    <tr>
                        <th>Required Date</th>
                        <td>{{ $order->required_date }}</td>
                    </tr>
                    <tr>
                        <th>Shipped Date</th>
                        <td>{{ $order->shipped_date ?? '' }}</td>
                    </tr>
                    <tr>
                        <th>Order Status</th>
                        <td>{{ config('app.order_status')[$order->order_status] ?? '' }}</td>
                    </tr>
                    <tr>
                        <th>Created at</th>
                        <td>{{ $order->created_at }}</td>
                    </tr>
                    <tr>
                        <th>Updated at</th>
                        <td>{{ $order->updated_at }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">
            Order Items
            <button type="button" class="btn btn-primary float-right btn-sm" data-toggle="modal" data-target="#addItemModel">
                <i class="fas fa-plus"></i> Add Items
            </button>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($order->order_items as $order_item)
                    <tr class="{{ $order_item->id }}">
                        <td>{{ $order_item->item->item_name }}</td>
                        <td>{{ $order_item->quantity }}</td>
                        <td>

                            <a href="#" class="btn btn-danger btn-sm" onclick="
                                var result = confirm('Are you sure you wish to DELETE {{ $order_item->item->item_name }}?');
                                if (result){
                                event.preventDefault();
                                $('#delete-item-{{ $order_item->id }}').submit();
                                }"><i class="far fa-trash-alt"></i></a>

                            <form id="delete-item-{{ $order_item->id }}"
                                  action="{{ route('orders.destroy_order_item', $order_item->id)}}" method="POST"
                                  style="display:none">
                                @csrf
                                @method('DELETE')
                                <input value="delete" name="_method" type="hidden">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="addItemModel" tabindex="-1" role="dialog" aria-labelledby="addItemModel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addItemModelTitle">Add Items to Order No: {{ $order->id }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{{ route('orders.store_order_item') }}">
                @csrf
                @method('POST')
                <div class="modal-body">
                    <input type="hidden" value="" id="selected_item_id" name="selected_item_id">
                    <input type="hidden" value="{{ $order->id }}" id="selected_order_id" name="selected_order_id">
                    <div class="form-group">
                        <label for="name">Item Name:</label>
                        <input type="text" class="form-control typeahead" name="item_name" id="item_name" required placeholder="Type Item Name" autocomplete="off"/>
                    </div>
                    <div class="form-group">
                        <label for="name">Quantity:</label>
                        <input type="number" class="form-control" name="quantity" id="quantity" pattern="[0-9]" required autocomplete="off"/>
                    </div>
                </div>
                <div class="modal-footer">
{{--                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>--}}
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>
    <script type="text/javascript">
        var path = "{{ route('item.autocomplete') }}";
        $('input.typeahead').typeahead({
            source:  function (query, process) {
                return $.get(path, { query: query }, function (data) {
                    return process(data);
                });
            },
            afterSelect: function(data){
                $('#selected_item_id').val(data.id);
            }
        });
    </script>
@endsection